logger:
  level: "debug"

app:
  database:
    host: "localhost"
    port: 4100
    name: "name"
    user: "user"
    password: "password"
    migrationspath: "migrations"

api:
  http:
    host: "localhost"
    port: "4200"
  grpc:
    port: 9090
  websocket:
    readbuffersize: 1024
    writebuffersize: 1024
    port: 7070